/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-5-16 下午9:21' with Gradle 2.14
 *
 * @author Administrator, @date 17-5-16 下午9:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
